### PR TITLE
Add icon

### LINKED ISSUE #33: Needs a proper icon
This was already discussed heavily in https://github.com/nextcloud/server/issues/856

@Bugsbane and @eppfel had already nice ideas.

@eppfel Did you finished the icon already?

### PR DESCRIPTION
**Pull request by MorrisJobke**
* was done by Felix (https://github.com/eppfel)
* I inverted it and ran an SVG optimizer
* see https://github.com/nextcloud/survey_client/issues/33#issuecomment-273759549
* fixed #33

bildschirmfoto 2017-01-19 um 12 45 05

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @skjnldsv @jancborchardt

**Comment by skjnldsv** [comment]
I like it. Seemed a little bit out of place, but I think this is because the icons are too big on the app store. Doesn't matter :)

**Comment by eppfel** [comment]
I found out what was wrong and fixed it: 😁 
bildschirmfoto 2017-01-20 um 00 44 35

**Comment by skjnldsv** [comment]
MUCH BETTER! 🎉

**Comment by jancborchardt** [comment]
Good modification @eppfel! :)

**Pull request merged**
