### PR TITLE
Fix the notification URLs when they where created too early

### PR DESCRIPTION
**Pull request by nickvergessen**
Let's backport this, to help prevent bad mood of people, that can not press **Not now** to get rid of the notification.

Fix nextcloud/server#1356

@schiessle please review so we can backport before the release on thursday

### CODE REVIEW

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/server/issues/1356

**Comment by schiessle** [comment]
makes sense :+1:

**Comment by schiessle** [comment]
@nickvergessen please prepare a backport for stable10, thanks!

**Comment by nickvergessen** [comment]
Done in #32

**Pull request merged**
