### PR TITLE
Name of the collector is `Php`.

### PR DESCRIPTION
**Pull request by kesselb**
https://github.com/nextcloud/survey_client/blob/a7b718b472b07e156f54ae4d1d40236fd58d71ad/lib/Categories/Php.php#L33

### CODE REVIEW

**Comment by kesselb** [comment]
Hmm. It still works with `php`. I'm not sure if we need to backport it ;)

**Comment by nickvergessen** [comment]
Well the change is so little, better save then sorry

**Comment by jospoortvliet** [comment]
Just being curious - does this fix the fact that the survey_client doesn't work since Nextcloud 14? At least our survey server has no data newer than that. It works on a local instance (at least doesn't give an error and updates when the report was last send), I've just tested it. But on my normal instance I still get 'An error occurred while sending your report.'. Sadly the logs say nothing and there's no command line way to call this either.

The console shows:

```
POST https://cloud.josandcamila.com:444/ocs/v2.php/apps/survey_client/api/v1//report?format=json 500 (Internal Server Error)
```

  | send | @ | jquery.js:8630
-- | -- | -- | --
  | ajax | @ | jquery.js:8166
  | (anonymous) | @ | admin.js?v=40d0545e-81:35
  | dispatch | @ | jquery.js:4435
  | _.handle | @ | jquery.js:4121

server log just gives:
```
192.168.1.167 - - [09/Nov/2019:22:29:10 +0100] "POST /ocs/v2.php/apps/survey_client/api/v1//report?format=json HTTP/1.1" 500 6066 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36"
```

I can report an issue?!?

AAAH I figured it out - disabling all info, then going through it, enabling again. It is the app list! If you disable that, the report is send.

Will create an issue.

**Pull request merged**
