### PR TITLE
fix: notifications link for mobile / desktop error generating errors in v30

### LINKED ISSUE #316: v30 regression: recurring logging of `Link of notification is not an absolute URL and does not work in mobile and desktop clients`
```
{"reqId":"DH567oSE5X6okdvhnDiW","level":2,"time":"2024-09-24T15:53:19+00:00","remoteAddr":"192.168.88.67","user":"ncadmin","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"Icon of notification is not an absolute URL and does not work in mobile and desktop clients [app: survey_client, subject: updated]","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"30.0.0.14","data":[],"id":"66f2e1cdf046c"}

{"reqId":"DH567oSE5X6okdvhnDiW","level":2,"time":"2024-09-24T15:53:19+00:00","remoteAddr":"192.168.88.67","user":"ncadmin","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"Link of notification is not an absolute URL and does not work in mobile and desktop clients [app: survey_client, subject: updated]","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"30.0.0.14","data":[],"id":"66f2e1cdf047b"}


{
  "reqId": "DH567oSE5X6okdvhnDiW",
  "level": 2,
  "time": "2024-09-24T15:53:19+00:00",
  "remoteAddr": "192.168.88.67",
  "user": "ncadmin",
  "app": "no app in context",
  "method": "GET",
  "url": "/ocs/v2.php/apps/notifications/api/v2/notifications",
  "message": "Link of notification is not an absolute URL and does not work in mobile and desktop clients [app: survey_client, subject: updated]",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
  "version": "30.0.0.14",
  "data": [],
  "id": "66f2e1cdf047b"
}

### PR DESCRIPTION
**Pull request by joshtrichards**
Fixes #316

EDIT: I guess this has been broken for awhile, but wasn't super apparent until the new notification logging added in nextcloud/server#44770

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Will fix tomorrow

**Review by nickvergessen — APPROVED** [review]

**Comment by La-Fabrique-Info** [comment]
Warnings are still happening... doesn't seem fixed for me.
NC Version: 30.0.0.14
survey_client version: 2.0.0
```json
{
    "reqId": "QYss6puhYbfWtBEO2goJ",
    "level": 2,
    "time": "2024-09-28T10:22:53+00:00",
    "remoteAddr": "********",
    "user": "*******",
    "app": "no app in context",
    "method": "GET",
    "url": "/ocs/v2.php/apps/notifications/api/v2/notifications",
    "message": "Icon of notification is not an absolute URL and does not work in mobile and desktop clients [app: survey_client, subject: updated]",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "version": "30.0.0.14",
    "data": [],
    "id": "66f7d914e838a"
}
```

**Comment by joshtrichards** [comment]
Well, yeah - the code was just merged. :) You have to wait until the next maintenance release (or apply it manually early: https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html)

**Comment by La-Fabrique-Info** [comment]
Sorry for not having mentioned it in my previous message but the modif file `lib/BackgroundJobs/AdminNotification.php` has been patched in my setup.

**Comment by nickvergessen** [comment]
We didn't fix the icon. I can do it Monday.
Thanks for reporting back!

**Comment by tccadam** [comment]
I upgraded to the latest version 31.0.8 today, and I've been looking at the logs and I am still seeing these warnings over and over:

Icon of notification is not an absolute URL and does not work in mobile and desktop clients [app: passwords, subject: upgrade_required]
Icon of notification is not an absolute URL and does not work in mobile and desktop clients [app: passwords, subject: new_client]
Icon of notification is not an absolute URL and does not work in mobile and desktop clients [app: passwords, subject: survey]

I spent hours trying to figure out what was causing them and trying to stop them and eventually I found this forum which to me looks like this was fixed in version 31.0.0 ? So I'm posting this to ask why I would still be seeing them or to ask if someone could tell me how to fix it.

Thanks,
Adam

**Pull request merged**
