### PR TITLE
Fix several issues

### PR DESCRIPTION
**Pull request by nickvergessen**
* SQLite3 DB size
* File sharing SQL error for MySQL

Similar to nextcloud/serverinfo#30

@MorrisJobke @blizzz @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
As discussed :+1:

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Backport?

**Comment by MorrisJobke** [comment]
> Backport?

Ah it is already in #23

**Pull request merged**
