### PR TITLE
feat(deps): Add Nextcloud 29 support on master

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by luka-nextcloud — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
`static-psalm-analysis-summary` is expected but not part of the CI anymore.

Workflows should be updated from nextcloud/.github and CI requirement adapted. I can do it but I’d need admin rights, @nickvergessen Do you have those?

**Comment by come-nc** [comment]
(Looking into this because this application is shipped and it breaks `nextcloud/updater` CI that a shipped application does not support current master.)

**Comment by nickvergessen** [comment]
> `static-psalm-analysis-summary` is expected but not part of the CI anymore.

Looking at https://github.com/nextcloud/survey_client/blob/master/.github/workflows/psalm.yml I guess it is quite old and updating it would add the missing check ^^

But I can remove it for now

**Comment by come-nc** [comment]
> > `static-psalm-analysis-summary` is expected but not part of the CI anymore.
> 
> Looking at [`master`/.github/workflows/psalm.yml](https://github.com/nextcloud/survey_client/blob/master/.github/workflows/psalm.yml?rgh-link-date=2024-01-23T10%3A36%3A37Z) I guess it is quite old and updating it would add the missing check ^^
> 
> But I can remove it for now

I pushed an update of the workflow but I think there is no summary in this one so requirement will need to be adapted anyway.

**Comment by come-nc** [comment]
```
PHP module GD not installed.
Please ask your server administrator to install the module.
```

I’ll update phpunit workflows as well :shrug:

**Comment by nickvergessen** [comment]
updated static away from summary

**Comment by come-nc** [comment]
```
 Neither PHPUnit nor PHPUnit integration tests are specified in composer.json scripts
Error: Process completed with exit code 1.
```
Modern workflows are too smart :laughing: 

Deleting the workflow as there are no unit tests.

**Comment by nickvergessen** [comment]
> Deleting the workflow as there are no unit tests.

Recommended step is to run it with `echo`
Because then at least the migrations got run and you can be sure the app can still be enabled:
https://github.com/nextcloud/nextcloud_announcements/blob/master/composer.json#L26

**Pull request merged**
