### PR TITLE
Add comments and system tags to stats

### PR DESCRIPTION
**Pull request by nickvergessen**
@schiessle

### CODE REVIEW

**Comment by nickvergessen** [comment]
@schiessle please lets get this in and backported for 10.0.2

**Comment by schiessle** [comment]
Whats wrong here:

````
PHP Fatal error:  Class 'OCA\Survey_Client\AppInfo\Application' not found in /home/travis/build/nextcloud/server/apps/survey_client/appinfo/routes.php on line 22
````

**Comment by nickvergessen** [comment]
It's the reason why https://github.com/nextcloud/survey_client/pull/39 was needed, will rebase

**Comment by schiessle** [comment]
:+1:

**Pull request merged**
