### PR TITLE
Do not call invalid function

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@rullzer Backport or not?

**Comment by rullzer** [comment]
Yes! I'm not sure how this slipped in. I can't find this in stable9 even :confused:

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/blob/master/lib/private/OCS/Result.php#L128

What is your probalum? https://www.youtube.com/watch?v=xrqdpaKSjCA

**Comment by nickvergessen** [comment]
So only broken in 14, since 
https://github.com/nextcloud/survey_client/pull/72 where the OCS\Result was replaced with a Http Response

**Pull request merged**
