### PR TITLE
fix encryption enabled check

### LINKED ISSUE #16: Reports always says encryption is enabled
I've just checked the data which is collected and see that it reports that encryption is enabled on this instance I just upgraded, but that's not the case, so the info collector must be tracking the wrong parameter.

### PR DESCRIPTION
**Pull request by blizzz**
Fixes #16 

Please review @oparoz @nickvergessen @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
👍

**Comment by blizzz** [comment]
@schiessle nice try :p

**Comment by nickvergessen** [comment]
Haha

**Comment by nickvergessen** [comment]
Backport?

**Comment by blizzz** [comment]
> Backport?

yupp

**Pull request merged**
