### PR TITLE
Spelling: ": Files"

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by comradekingu** [comment]
It could be argued that the order should be alphabetical. It would also avoid confusion with other use of "Files".

**Comment by MorrisJobke** [comment]
cc @jancborchardt @nickvergessen

**Comment by jancborchardt** [comment]
I’d rather just remove the `:` than capitalize »files«. It makes it a simple sentence.

**Comment by MorrisJobke** [comment]
> I’d rather just remove the : than capitalize »files«. It makes it a simple sentence.

#79

**Pull request merged**
